apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: pulumi-operator
build:
  artifacts:
  - image: keppel.eu-de-1.cloud.sap/ccloud/cci-esxi-pulumi-go
deploy:
  kubectl:
    manifests:
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    defaultNamespace: cci-provision
