apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ccmaas-operator
build:
  artifacts:
    - image: keppel.eu-de-1.cloud.sap/ccloud/ccmaas-operator
      sync:
        manual:
          - src: "projects/esxi/*.go"
            dest: "projects"
            strip: "projects/"
          - src: "bin/ccmaas_linux_amd64"
            dest: "../bin"
            strip: "bin/"
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
    defaultNamespace: ccmaas
