apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: automation
profiles:
  - name: debug
    build:
      artifacts:
        - image: keppel.eu-de-1.cloud.sap/ccloud/vcf-automation
      tagPolicy:
        sha256: {}
    deploy:
      kubectl:
        manifests:
          - k8s/pod-debug.yaml
        defaultNamespace: vcf
  - name: dev
    build:
      artifacts:
        - image: keppel.eu-de-1.cloud.sap/ccloud/vcf-automation
          sync:
            infer:
              - "projects/**/*.py"
    deploy:
      kubectl:
        manifests:
          - k8s/pod-dev.yaml
        defaultNamespace: ccmaas
