apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: automation
build:
  artifacts:
    - image: keppel.eu-de-1.cloud.sap/ccloud/vcf-automation
      sync:
        manual:
          - src: "bin/automation_linux_amd64"
            dest: "../bin"
            strip: "bin/"
deploy:
  kubectl:
    manifests:
      - k8s/pod.yaml
      - k8s/service.yaml
      - k8s/ingress.yaml
    defaultNamespace: ccmaas
