apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vcf-automation
spec:
  selector:
    matchLabels:
      app: vcf-automation
  template:
    metadata:
      labels:
        app: vcf-automation
    spec:
      containers:
        - name: automation
          image: keppel.eu-de-1.cloud.sap/ccloud/vcf-automation:latest
          command:
            - "/pulumi/bin/automation"
            - "server"
          env:
            - name: PULUMI_BACKEND_URL
              value: file:///pulumi/automation/etc
            - name: PULUMI_CONFIG_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: vcf-secrets
                  key: pulumi_config_passphrase
            - name: AUTOMATION_PORT
              value: "8080"
            - name: AUTOMATION_OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcf-secrets
                  key: os_password
            - name: AUTOMATION_OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcf-secrets
                  key: os_username
            - name: AUTOMATION_OS_REGION
              value: eu-de-1
            - name: AUTOMATION_VMWARE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcf-secrets
                  key: vmware_password
            - name: AUTOMATION_WORK_DIR
              value: /pulumi/automation
            - name: AUTOMATION_PROJECT_ROOT
              value: /pulumi/automation/projects
            - name: AUTOMATION_CONFIG_DIR
              value: /pulumi/automation/etc
            - name: AUTOMATION_STATIC_PATH
              value: /pulumi/automation/static
            - name: AUTOMATION_TEMPLATE_PATH
              value: /pulumi/automation/templates
          volumeMounts:
            - mountPath: /pulumi/automation/etc
              subPath: etc
              name: pvc
          ports:
            - containerPort: 8080
              name: api
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: vcf-workspace
