apiVersion: v1
kind: Pod
metadata:
  name: avocado-automation-test
  labels:
    app: avocado-automation
spec:
  containers:
    - name: automation
      image: keppel.eu-de-1.cloud.sap/ccloud/avocado-automation:latest
      command:
        - "/pulumi/bin/automation"
        - "server"
      env:
        - name: PULUMI_CONFIG_PASSPHRASE
          value: pass4config
        - name: PULUMI_BACKEND_URL
          value: file:///pulumi/avocado/etc
        - name: AUTOMATION_PORT
          value: "8080"
        - name: AUTOMATION_OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccmaas-pass
              key: os_password
        - name: AUTOMATION_OS_USERNAME
          valueFrom:
            secretKeyRef:
              name: ccmaas-pass
              key: os_username
      volumeMounts:
        - mountPath: /pulumi/avocado/etc
          subPath: etc
          name: pvc
      ports:
        - containerPort: 8080
          name: api
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: ccmaas-workspace
